collectionspace/application

- tomcat-main/src/main/resources/defaults/extensions/fineart-authority-concept.xml
- tomcat-main/src/main/resources/defaults/extensions/fineart-collectionobject.xml
- tomcat-main/src/main/resources/defaults/extensions/fineart-vocabularies.xml
- tomcat-main/src/main/resources/defaults/extensions/variablemedia-collectionobject.xml
- tomcat-main/src/main/resources/defaults/extensions/variablemedia-procedure-conditioncheck.xml
- tomcat-main/src/main/resources/defaults/extensions/variablemedia-vocabularies.xml
- tomcat-main/src/main/resources/fcart-tenant.xml
- tomcat-main/src/main/resources/tenants/fcart/domain-instance-vocabularies.xml
- tomcat-main/src/main/resources/tenants/fcart/settings.xml
Adds config for Variable Media Extension, Fine Art Extension, and config and example tenant for Fine and Contemporary Art Profile.
> Fine contemporary profile

- tenant.properties
> Add verbose examples of tenant property values

- tomcat-main/src/main/resources/defaults/extensions/variablemedia-vocabularies.xml
Fields used by condition support now display in Term List Mgmt
> Fixes CSPACE-6687

- cspi-services/src/test/java/org/collectionspace/chain/csp/persistence/services/TestService.java
- cspi-services/src/test/resources/org/collectionspace/chain/csp/persistence/services/conservation.json
- cspi-services/src/test/resources/org/collectionspace/chain/csp/persistence/services/conservation.xml
- tomcat-main/src/main/resources/core-tenant.xml
- tomcat-main/src/main/resources/default.xml
- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/base-other-idgenerator.xml
- tomcat-main/src/main/resources/defaults/base-procedure-conservation.xml
- tomcat-main/src/main/resources/defaults/base-relations.xml
- tomcat-main/src/main/resources/defaults/domain-procedure-conservation.xml
- tomcat-main/src/main/resources/fcart-tenant.xml
- tomcat-main/src/main/resources/lifesci-tenant.xml
- tomcat-main/src/test/java/org/collectionspace/chain/csp/persistence/TestData.java
- tomcat-main/src/test/java/org/collectionspace/chain/csp/webui/main/TestUIRecords.java
- tomcat-main/src/test/resources/org/collectionspace/chain/csp/persistence/conservation-search.uischema
- tomcat-main/src/test/resources/org/collectionspace/chain/csp/persistence/conservation-search.uispec
- tomcat-main/src/test/resources/org/collectionspace/chain/csp/persistence/conservation.uischema
- tomcat-main/src/test/resources/org/collectionspace/chain/csp/persistence/conservation.uispec
- tomcat-main/src/test/resources/org/collectionspace/chain/csp/persistence/conservationCreate.json
- tomcat-main/src/test/resources/org/collectionspace/chain/csp/persistence/recordlist.uischema
- tomcat-main/src/test/resources/org/collectionspace/chain/csp/persistence/recordtypes.uischema
Awaiting final approval from Megan/community.
> CSPACE-6902: Add conservation procedure.

- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
> Lower-case process and property terms & add some more

- cspi-services/src/main/java/org/collectionspace/chain/csp/persistence/services/vocab/ConfiguredVocabStorage.java
- cspi-webui/src/main/java/org/collectionspace/chain/csp/webui/authorities/VocabulariesWorkflowTransition.java
- cspi-webui/src/main/java/org/collectionspace/chain/csp/webui/main/WebUI.java
- cspi-webui/src/main/java/org/collectionspace/chain/csp/webui/misc/WebAutoComplete.java
- tomcat-main/src/main/resources/defaults/core-fields.xml
Add support for deactivating authority items.
> CSPACE-6955

- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/base-procedure-objectexit.xml
Work completed June 2016 for LYRASIS
> adding Deaccession and Disposal fields to Object Exit procedure

- tomcat-main/src/main/resources/core-tenant.xml
- tomcat-main/src/main/resources/default.xml
- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/base-procedure-insurance.xml
- tomcat-main/src/main/resources/defaults/domain-procedure-insurance.xml
Resolves: https://collectionspace.atlassian.net/browse/DRYD-944
> DRYD-944: Create Insurance/Indemnity procedure

- tomcat-main/src/main/resources/defaults/extensions/checklist-procedure-group.xml
- tomcat-main/src/main/resources/defaults/extensions/checklist-vocabularies.xml
- tomcat-main/src/main/resources/publicart-tenant.xml
- tomcat-main/src/main/resources/tenants/publicart/domain-instance-vocabularies.xml
Resolves: https://collectionspace.atlassian.net/browse/DRYD-940
> DRYD-940: Add checklist extension

- tomcat-main/src/main/resources/lhmc-tenant.xml
Resolves: https://collectionspace.atlassian.net/browse/DRYD-959
> DRYD-959: Enable Use of Collections procedure in LHMC

- tomcat-main/src/main/resources/anthro-tenant.xml
- tomcat-main/src/main/resources/bonsai-tenant.xml
- tomcat-main/src/main/resources/fcart-tenant.xml
- tomcat-main/src/main/resources/herbarium-tenant.xml
- tomcat-main/src/main/resources/lhmc-tenant.xml
Enables Transport/Insurance/UOC procedures in the following profiles:
* Anthropology: Transport and I/I
* Bonsai: Transport, I/I, and Use of Collections
* FCART: Transport and I/I
* Herbarium: Transport, I/I and Use of Collections
* LHMC: Transport, I/I
> DRYD-990: Enable Transport / Insurance / Use of Collections

- tomcat-main/src/main/resources/defaults/base-authority-material.xml
Create repeatable field group for `featuredCollection` and note for material authority
> DRYD-981: Add featuredCollection field group

- tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
Resolves: https://collectionspace.atlassian.net/browse/DRYD-1009
> DRYD-1009: Add insurance/indemnity to fcart vocab

- tomcat-main/src/main/resources/core-tenant.xml
- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/base-procedure-iterationreport.xml
- tomcat-main/src/main/resources/defaults/domain-procedure-iterationreport.xml
- tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
Jira Ticket: https://collectionspace.atlassian.net/browse/DRYD-1036
Adds procedure and vocab for core + fcart
> DRYD-1036: Create iterationreport procudure

- tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
Jira: https://collectionspace.atlassian.net/browse/DRYD-1062
> DRYD-1062: Add annotation type to fcart vocab

- tomcat-main/src/main/resources/defaults/base-collectionobject.xml
- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1061 
* Fix typo in contract address
* Make API URL field repeatable
* Change Credential Location to a text field
* Add chroma subsampling + vocab
* Add channel type
* Add still to formattype vocab
* Add technical attributes + vocab for av and software sections
> DRYD-1061: Updates to TimeBasedMedia fields

- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/base-procedure-iterationreport.xml
- tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
Jira: https://collectionspace.atlassian.net/browse/DRYD-1064
Updates to IterationReport
* Populate Iteration Report Summary field with primary value of Iteration Creator field.
* Add new iteration action group fields
* Add 'Artist or representative' field
* Update Artist Presence vocab
> DRYD-1064: Updates to iteration report

- tomcat-main/src/main/resources/defaults/base-collectionobject.xml
- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/base-procedure-media.xml
- tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
Jira Ticket: https://collectionspace.atlassian.net/browse/DRYD-1035
Also added to collectionobject per https://collectionspace.atlassian.net/browse/DRYD-1061
> DRYD-1035: Add checksum fields to media handling and collectionobject

- tomcat-main/src/main/resources/defaults/base-authority-person.xml
- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
Jira: https://collectionspace.atlassian.net/browse/DRYD-1066
Note: The terms in the spreadsheet are supposed to be dynamic, but there were already some terms defined in the ui (e.g. for gender) so I opted to do them all there
> DRYD-1066: Add maker supplied identity info

- tomcat-main/src/main/resources/defaults/base-collectionobject.xml
- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
Jira: https://collectionspace.atlassian.net/browse/DRYD-1065
> DRYD-1065: Copyright extension for collectionobject

- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/extensions/variablemedia-vocabularies.xml
Vocab updates for DRYD-1033:
* Additional placeholder values for QA testing
* Migrate programminglanguage from variable media to core
> DRYD-1033: Vocab updates

- tomcat-main/src/main/resources/fcart-tenant.xml
Jira: https://collectionspace.atlassian.net/browse/DRYD-1121
> DRYD-1121: Add iterationreport to fcart

- tomcat-main/src/main/resources/tenants/materials/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/tenants/publicart/base-instance-vocabularies.xml
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1035 
* Add checksumtype vocab to publicart and materials
> DRYD-1035: Add checksum to media handling

- tomcat-main/src/main/resources/tenants/publicart/base-instance-vocabularies.xml
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1066
> DRYD-1066: Enable maker supplied vocab for publicart

- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
- tomcat-main/src/main/resources/tenants/botgarden/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/tenants/publicart/base-instance-vocabularies.xml
Jira(s): https://collectionspace.atlassian.net/browse/DRYD-1122, https://collectionspace.atlassian.net/browse/DRYD-1152
I know we capitalize proper nouns, but wasn't sure about acronyms/initialisms (or mixes... e.g. `Adobe RGB`).
> Default values for TBM and Iteration Report vocabs

- tomcat-main/src/main/resources/defaults/base-collectionobject.xml
- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
Jira: https://collectionspace.atlassian.net/browse/DRYD-1171
* Rename objectComponentStatus
* Update name for component status vocab
> DRYD-1171: Rename objectComponentStatus

- tomcat-main/src/main/resources/defaults/base-authority-person.xml
Jira: https://collectionspace.atlassian.net/browse/DRYD-1172
* Rename supplied birth date fields to avoid conflict with previously defined birthDateGroup
> DRYD-1172: Rename supplied birth date fields to avoid conflict

- tomcat-main/src/main/resources/defaults/base-collectionobject.xml
- tomcat-main/src/main/resources/defaults/base-procedure-iterationreport.xml
Jira: https://collectionspace.atlassian.net/browse/DRYD-1173
* Updates TBM fields in collectionobject to use correct attributes
* Updates iterationreport fields to use correct attributes
> DRYD-1173: 500 error for some TBM fields

- tomcat-main/src/main/resources/defaults/base-collectionobject.xml
@ray-lee One more for 1173 that I caught double checking against the config w/ jq.
> DRYD-1173: Fix attrs for domainOwner

- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
* Renames Required Application to Interacting Application
> Rename vocab for Interacting Application

- tomcat-main/src/main/resources/defaults/base-procedure-loanin.xml
- tomcat-main/src/main/resources/defaults/base-procedure-loanout.xml
Jira: https://collectionspace.atlassian.net/browse/DRYD-1191 + https://collectionspace.atlassian.net/browse/DRYD-1192
* DRYD-1191: Add creditLine to loanin
* DRYD-1192: Add creditLine to loanout
> Add creditLine to loanin and loanout

- tomcat-main/src/main/resources/defaults/base-collectionobject.xml
Jira: https://collectionspace.atlassian.net/browse/DRYD-1167
> DRYD-1167: Add controlled material

- tomcat-main/src/main/resources/defaults/base-collectionobject.xml
Jira: https://collectionspace.atlassian.net/browse/DRYD-1128
* Add controlled object name to collectionobject
> DRYD-1128: Add controlled object name

- tomcat-main/src/main/resources/materials-tenant.xml
This enables the valuation procedure in the materials tenant.
https://collectionspace.atlassian.net/browse/DRYD-1275
- Start Collectionspace.
- In a browser, go to http://localhost:8180/cspace-services/servicegroups/procedure, and log in as admin@materials.collectionspace.org 
The result should include `<hasDocType>Valuationcontrol</hasDocType>`
- Go to http://localhost:8180/cspace-services/valuationcontrols
A result list should be returned without error.
None.
n/a …
> DRYD-1275: Enable valuation procedure in materials tenant.

- tomcat-main/src/main/resources/core-tenant.xml
- tomcat-main/src/main/resources/default.xml
- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/base-procedure-dutyofcare.xml
- tomcat-main/src/main/resources/defaults/domain-procedure-dutyofcare.xml
* Creates the DutyOfCare procedure
* Adds duty of care term lists
Jira: https://collectionspace.atlassian.net/browse/DRYD-1332
This is one of the procedures for the NAGPRA support we're working on for the next release.
* Run the test suite against collectionspace
The `dutyofcareroles` terms still need to be defined
No
@mikejritter tested the procedure through the ui updates
> Add DutyOfCare Procedure

- tomcat-main/src/main/resources/core-tenant.xml
- tomcat-main/src/main/resources/default.xml
- tomcat-main/src/main/resources/defaults/base-authority-concept.xml
- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/base-procedure-nagpraclaim.xml
- tomcat-main/src/main/resources/defaults/domain-procedure-nagpraclaim.xml
* Creates nagpra claim procedure
* Adds additional vocabularies for claim workflows
* Add ethculture to concept authority
Jira: https://collectionspace.atlassian.net/browse/DRYD-1330
This is the new claim procedure for the 8.1 release which will better support NAGPRA workflows.
* Start the tomcat server for collectionspace
* Run integration tests against the running collectionspace
None
No
@mikejritter built collectionspace and deployed to a local …
> DRYD-1330: Add NAGPRA Claim

- tomcat-main/src/main/resources/core-tenant.xml
- tomcat-main/src/main/resources/default.xml
- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
- tomcat-main/src/main/resources/defaults/base-procedure-nagprainventory.xml
- tomcat-main/src/main/resources/defaults/domain-procedure-nagprainventory.xml
* Create nagpra inventory procedure 
* Add new terms needed for nagpra inventory
Jira: https://collectionspace.atlassian.net/browse/DRYD-1331
* Build collectionspace with the services pr for nagpra inventory and all tenants needed for running the integration tests
* Run the integration test suite
None
No
> DRYD-1331: NAGPRA Inventory

- tomcat-main/src/main/resources/anthro-tenant.xml
* Enables the following procedures in anthro
* Claim  
* DutyOfCare
* Inventory
* SummaryDocumentation
* HeldInTrust
* Consultation
Jira: https://collectionspace.atlassian.net/browse/DRYD-1449
This is to allow for a preview of the new NAGPRA workflow procedures in the anthro profile on dev.
* Test that the procedures are able to be accessed from the anthro profile, e.g.
```
[$] curl -u 'admin@anthro.collectionspace.org:Administrator' http://localhost:8180/cspace-services/repatriationclaims
[$] curl -u 'admin@anthro.collectionspace.org:Administrator' http://localhost:8180/cspace-services/summarydocumentations
[$] curl …
```
> DRYD-1449: Enable Some NAGPRA Procedures in Anthro

- cspi-installation/src/main/java/org/collectionspace/chain/installation/ServiceBindingsGeneration.java
- cspi-schema/src/main/java/org/collectionspace/chain/csp/schema/Record.java
- tomcat-main/src/main/resources/defaults/base-procedure-consultation.xml
- tomcat-main/src/main/resources/defaults/base-procedure-dutyofcare.xml
- tomcat-main/src/main/resources/defaults/base-procedure-heldintrust.xml
- tomcat-main/src/main/resources/defaults/base-procedure-nagprainventory.xml
- tomcat-main/src/main/resources/defaults/base-procedure-repatriationclaim.xml
- tomcat-main/src/main/resources/defaults/base-procedure-summarydocumentation.xml
* Add tag attribute to Record
* Add nagpra tag to all NAGPRA procedures
* Update ServiceBindingGeneration to add tag section
Jira: https://collectionspace.atlassian.net/browse/DRYD-1393
These are changes that allow us to use a `tag` query on a subset of procedures, normally when searching for relations. The use case for this is the NAGPRA procedures which we want to create a sidebar for, and will do so by updating the base procedures in the application layer to have an additional `nagpra` tag. 
In the application layer this is done by allowing the `base-procedure` schemas to include a `tag` attribute which can be used to populate the service binding. Any number of tags can be added using commas to separate them, similar to …
> DRYD-1393: Tag attribute for procedures

- tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
* Update NAGPRA Determination Types
* Update Grave Assoc Code term
Jira: https://collectionspace.atlassian.net/browse/DRYD-1430
These are clarifications for some of the new term lists which came from discussion in the jira.
* Rebuild and deploy CollectionSpace
* See the updated term lists 
None
No
...also no
> DRYD-1430: Updates for NAGPRA Terms

- pom.xml
* Updates build release to 8.1.1
No jira
This is part of the release process for cspace.
* Build and start collectionspace
None
No
@mikejritter built locally
> Update Version to 8.1.1
