tomcat-main/src/main/resources/core-tenant.xml
tomcat-main/src/main/resources/default.xml
tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/base-procedure-transport.xml
tomcat-main/src/main/resources/defaults/domain-procedure-transport.xml

Resolves: https://collectionspace.atlassian.net/browse/DRYD-943
Adds Transport procedure xml and new vocab for specified controlled lists.
Note: I just noticed that the formatting is a bit funky in the `core-tenant` and `base-instance-vocab` files when creating this. Let me know if this is an issue and I can get them straightened out before merging.

DRYD-943: Add Transport Procedure

---

tomcat-main/src/main/resources/defaults/base-collectionobject.xml
tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml

Fields + vocab defined in:
* https://collectionspace.atlassian.net/browse/DRYD-1034
* https://collectionspace.atlassian.net/browse/DRYD-1039
* https://collectionspace.atlassian.net/browse/DRYD-1040
* https://collectionspace.atlassian.net/browse/DRYD-1041
There are still some missing vocabulary entries in the specs from the epic (https://collectionspace.atlassian.net/browse/DRYD-1033), so I've only added placeholders for them. These are: `softwarelibraries`, `connectiontype`, `domaintype`, `requiredapplication`, `compressionstandards`, and `colortypes`.
There's also a controlled list defined in the spec for saying something is required, which is typically just a yes/no. I was considering just using a single vocab item for this but wasn't sure what is preferred.

TimeBasedMedia fields for Cataloging

---

tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/cspace-vocabs.xml
tomcat-main/src/main/resources/defaults/extensions/fineart-vocabularies.xml
tomcat-main/src/main/resources/defaults/extensions/livingplant-vocabularies.xml
tomcat-main/src/main/resources/defaults/extensions/variablemedia-vocabularies.xml
tomcat-main/src/main/resources/tenants/materials/base-instance-vocabularies.xml

- Add terms as per [(DRYD-1049) Update Work Authority term lists for Materials profile](https://collectionspace.atlassian.net/browse/DRYD-1049)
- Make vocabulary title elements consistently human-readable (i.e. Person Term Types not personTermTypes, or Electrical Properties not electricalproperties). I did this in the defaults where applicable, assuming the changes would cascade down to profiles/tenants. 
- Remove leading/trailing spaces from vocabulary term values (i.e. `<option id="unknown"> unknown </option>`)
- Corrected a typo in term value (left the incorrect spelling in the option id attribute)

Dryd 1049 materials vocab terms

---

tomcat-main/src/main/resources/defaults/base-collectionobject.xml

JIRA(s): 
* https://collectionspace.atlassian.net/browse/DRYD-1135
* https://collectionspace.atlassian.net/browse/DRYD-1143
* DRYD-1135: Update programmingLanguage field to avoid conflict with fcart
* DRYD-1143: Add additional context to library and compiler fields

DRYD-1135: Rename TBM fields

---

tomcat-main/src/main/resources/core-tenant.xml
tomcat-main/src/main/resources/defaults/base-authority-chronology-termList.xml
tomcat-main/src/main/resources/defaults/base-authority-chronology.xml
tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/domain-authority-chronology.xml

Creates a new Chronology Authority
https://collectionspace.atlassian.net/browse/DRYD-1133
_Note: Specs are in DRYD-1134_
This new authority allows records to reference eras (e.g. archaeological, geological, historical, etc) and events (e.g. presidential terms, wars, olympic games, etc).
* Verify that cspace is able to build and deploy;
* Once the server is running check that the authority and vocabularies are able to be queried, e.g.
* curl -u 'admin@core.collectionspace.org:Administrator' http://localhost:8180/cspace-services/chronologyauthorities
* curl -u 'admin@core.collectionspace.org:Administrator' …

DRYD-1133: Chronology Authority

---

tomcat-main/src/main/resources/defaults/extensions/nagpra-collectionobject.xml

Add repeatable field for notes to the nagpra collection object extension
https://collectionspace.atlassian.net/browse/DRYD-1211
Allows capturing of generic notes for NAGPRA objects.
Using the PR from cspace-ui-plugin-ext-nagpra.js and the athro ui plugin:
* Build collection space with the `anthro` tenant enabled from this PR
* Build the PR for the nagpra ui extension: `npm run build`
* Copy the dist directory from the ui extension into the anthro node_modules, e.g. `node_modules/cspace-ui-plugin-ext-nagpra.js`
* Side note - not sure if there's a better/easier way of doing this but it's how I've been testing changes for the ui projects
* Run the anthro …

DRYD-1211: Add nagpra note field

---

tomcat-main/src/main/resources/anthro-tenant.xml
tomcat-main/src/main/resources/defaults/base-collectionobject.xml
tomcat-main/src/main/resources/tenants/anthro/anthro-collectionobject.xml

Enable Chronology for the Anthro profile
Adds fields to CollectionObject which will use the Chronology authority
The fields are defined in the spec for [DRYD-1133](https://collectionspace.atlassian.net/jira/software/c/projects/DRYD/issues/DRYD-1133).
* Build collectionspace
* Using the adjacent PR from cspace-ui, try to create and save a collectionobject with new fields:
* objectProductionEra
* assocControlledEventName
* assocControlledEventType
None
No
@mikejritter tested …

DRYD-1133: Add chronology fields to collectionobject

---

tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml

Updates default chronology terms
Jira: https://collectionspace.atlassian.net/jira/software/c/projects/DRYD/issues/DRYD-1216
The initial creation of the chronology authority was missing default terms. This sets the default terms from a curated list.
* Rebuild collectionspace using this PR
* Check that the chronology vocabularies exist 
None
No
@mikejritter rebuilt and checked the new vocabs exist in core

DRYD-1216: Add chronology vocabs

---

cspi-schema/src/main/java/org/collectionspace/chain/csp/schema/Record.java

This fixes a bug in the generation of xsd (XML schema) files from the application config files. When the application config contains fields with the same name in multiple schema, those fields are omitted from some of the generated xsd files. The fields that should appear in multiple xsd files only appear in one.
This happens because when the application config files are parsed, fields are stored in a map keyed by name, and later retrieved from the map when generating the xsd files. When multiple fields in different schema have the same name, they overwrite each other in the map, since the key is only the local name, not a schema-qualified name. This is fixed by schema-qualifying the key in the map.
Note that the parsing code contains other similar maps, which are …

DRYD-989: Fix incorrect XSD generation.

---

tomcat-main/src/main/resources/tenants/publicart/publicart-authority-concept.xml

This enables the Associated Concept authority in the public art profile. Previously, this had been disabled.
This supports the Artist Tag field, which will be tied to the Associated Concept authority. 
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1015
List the concept authorities in the public art tenant using the REST API. The Associated Concepts authority should be present (along with Material Concepts and Work Types):
```
$ curl -s -u admin@publicart.collectionspace.org:Administrator http://localhost:8180/cspace-services/conceptauthorities -H 'Accept: application/json' | jq
{
"ns2:abstract-common-list": {
"@xmlns:ns2": …
```

DRYD-1015: Enable associated concept authority in public art.

---

tomcat-main/src/main/resources/defaults/base-authority-place.xml
tomcat-main/src/main/resources/defaults/base-collectionobject.xml

* Adds archaeological site to place authority
* Add fieldCollectionSite to collectionobject
Jira: https://collectionspace.atlassian.net/browse/DRYD-1217?filter=17813
For this PR, just build collectionspace and ensure it succeeds. Usage will be handled in the cspace-ui PR.
Just a note that this doesn't add the associated authorities as those will be completed at a later point in time.
No
@mikejritter tested the changes

DRYD-1217: Archaeological site

---

tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
tomcat-main/src/main/resources/fcart-tenant.xml
tomcat-main/src/main/resources/lhmc-tenant.xml
tomcat-main/src/main/resources/tenants/botgarden/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/materials/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/publicart/base-instance-vocabularies.xml

* Adds chronology to fcart and lhmc tenants
* Syncs chronology vocabs with all tenants 
Jira: https://collectionspace.atlassian.net/browse/DRYD-1133
Requested in most recent comment to enable chronology for fcart and lhmc
* Build collectionspace with core, fcart, lhmc, and anthro profiles enabled
* Run collectionspace and test the chronology vocabs exist and the authority can be created
None
No
@mikejritter tested against fcart and lhmc

DRYD-1133: Add chronology to fcart and lhmc

---

tomcat-main/src/main/resources/defaults/base-collectionobject.xml
tomcat-main/src/main/resources/defaults/extensions/fineart-authority-concept.xml
tomcat-main/src/main/resources/tenants/anthro/anthro-collectionobject.xml

* Adds controlled contentEvent to collectionobject
* Make assocEvent repeatable
* Remove assocEventType
* Add nomenclature concept to fcart
Changes were requested for the assocEvent field to make it repeating and have the assocEventType removed. Along with this contentEvent was requested to be added. 
Nomenclature is being added to the fineart concepts as it is needed in order to be used by the controlled object name field.
Controlled event jira: https://collectionspace.atlassian.net/browse/DRYD-1238
Controlled obj name jira: https://collectionspace.atlassian.net/browse/DRYD-1128
Testing mostly done in the cspace-ui projects, but the vocabulary can be …

Controlled Events and fcart Nomenclature

---

tomcat-main/src/main/resources/anthro-tenant.xml
tomcat-main/src/main/resources/defaults/base-authority-chronology.xml
tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/anthro/anthro-authority-chronology.xml

* Updates to chronology field names so that they're consistent with the ui names
* Move the chronology fieldcollection authority to anthro
* Remove the associated authority block so that it can be re-spec'd
* https://collectionspace.atlassian.net/browse/DRYD-1261
* https://collectionspace.atlassian.net/browse/DRYD-1264
* https://collectionspace.atlassian.net/browse/DRYD-1267
This brings in a few changes from QA which were identified as bringing more consistency to the chronology authority as well as tenant deployments. In addition, the associated authorities block was seen as still needing more work before it's ready for production and as such has been removed from the chronology authority as well as having its …

7.2 QA Updates

---

.gitignore
cspi-installation/src/main/java/org/collectionspace/chain/installation/ServiceConfigGeneration.java
tomcat-main/logged_schemas/.gitignore
tomcat-main/logs/.gitignore
tomcat-main/logs/README.txt
tomcat-main/src/main/resources/defaults/base-procedure-exhibition.xml
tomcat-main/src/main/resources/tenants/anthro/domain-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/botgarden/base-procedure-pottag.xml
tomcat-main/src/main/resources/tenants/core/settings.xml

* Add anthroassertionnames vocab
* Log schemas if debug logging is enabled
* Add mini=number to commonName for pottag
* Set name for core repository
* Updates to .gitignore
Jira: https://collectionspace.atlassian.net/browse/DRYD-1268
This is part of the UCB contributions. I haven't really looked over this one too much, the only thing I did was pull in various changes that weren't audit or Held-in-Trust. The `anthroassertionnames` vocab which was from their annotation-collectionobject extension commit.
* Build collectionspace
* Check that the anthroassertionnames vocab exists
* Check the mini display for pottag commonName is correct
**Dependencies for …

DRYD-1268: UCB Misc Contrib

---

tomcat-main/src/main/resources/anthro-tenant.xml
tomcat-main/src/main/resources/bonsai-tenant.xml
tomcat-main/src/main/resources/botgarden-tenant.xml
tomcat-main/src/main/resources/core-tenant.xml
tomcat-main/src/main/resources/default.xml
tomcat-main/src/main/resources/defaults/base-authority-chronology.xml
tomcat-main/src/main/resources/defaults/base-authority-person.xml
tomcat-main/src/main/resources/defaults/base-authority-place.xml
tomcat-main/src/main/resources/defaults/base-other-associatedauthority.xml
tomcat-main/src/main/resources/fcart-tenant.xml
tomcat-main/src/main/resources/herbarium-tenant.xml
tomcat-main/src/main/resources/lhmc-tenant.xml
tomcat-main/src/main/resources/materials-tenant.xml
tomcat-main/src/main/resources/publicart-tenant.xml
tomcat-main/src/main/resources/tenants/botgarden/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/materials/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/publicart/base-instance-vocabularies.xml
tomcat-main/src/main/resources/testsci-tenant.xml

This adds the associated authorities block to chronology, person, and place authorities. 
Jira: https://collectionspace.atlassian.net/browse/DRYD-1286
The associated authorities were mostly complete for 7.2 but changes were held off for the release. This adds them to the three authorities listed above  
Along with the cspace-ui PR:
* Rebuild collectionspace so that the associated authorities block is included in chronology, person, and place
* Create a chronology, place, and person
* When creating add an associated authority
* Verify that the authority saves and reloads correctly  
Since these …

DRYD-1286: Create associated authorities fields

---

tomcat-main/src/main/resources/defaults/base-collectionobject.xml
tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml

Adds a new group for object count fields and vocabulary for the object count type
Jira: https://collectionspace.atlassian.net/browse/DRYD-1316
This is intended to replace the `numberOfObjects` field with a more complete set of fields to support reporting needs for archaeology and NAGPRA profiles. 
* See that the new term list exists under `objectcounttypes`
* Create a collectionobject using the new fields and term
As this is only the first part of the work to replace `numberOfObjects`, there are still changes which will be required in the services layer and other places to …

DRYD-1316: Add object count fields and vocabulary

---

tomcat-main/src/main/resources/defaults/base-authority-organization.xml

Adds nameNote to organization
Jira: https://collectionspace.atlassian.net/browse/DRYD-1206
This adds a field for storing information about organization authorities which other authorities already have.
* Using the cspace-ui PR create an organization authority with the nameNote filled out
* Verify that the new field saves
None
No
@mikejritter tested against a local install

DRYD-1206: Add nameNote field

---

tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/botgarden/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/materials/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/publicart/base-instance-vocabularies.xml

Adds `objectcounttypes` vocabulary to all tenants
This is being done for https://collectionspace.atlassian.net/browse/DRYD-1374 where objectCount is being added in to each template which has been overridden. This work allows the `objectCountType` field to be populated for the term picker input.  
* rebuild collectionspace with the fcart, materials, and publicart tenants enabled
* see that `objectcounttypes` exists for each tenant
* e.g. `curl -u admin@anthro.collectionspace.org:Administrator "http://localhost:8180/cspace-services/vocabularies/urn:cspace:name(objectcounttypes)"`
None
**Has the …

DRYD-1374: Add objectcounttypes to all tenant vocabs

---

tomcat-main/src/main/resources/defaults/base-other-associatedauthority.xml

* Adds assoc prefix to associated authorities fields
Jira: https://collectionspace.atlassian.net/browse/DRYD-1286
This helps with fields in the schema which may have the same name, e.g. `chronologies_common.chronologyNote` and `assocCronlogyAuthGroupList/assocChronologyAuthGroup.chronlogyNote`. By adding a prefix we're removing the possibility of this collision, as we will have `assocChronlogyAuthGroupList/assocChronologyAuthGroup.assocChronlogyNote`.
* Using the related cspace-ui PR, verify that associated authorities save
None
**Has the application documentation been …

Associated Authority Field Prefix

---

tomcat-main/src/main/resources/defaults/base-collectionobject.xml

Creates a repeating field for fieldCollectionPlace
Jira: https://collectionspace.atlassian.net/browse/DRYD-1395
This updates filedCollectionPlace so that it can be repeatable, which was requested in the associated JIRA.
* Check that the database tables exist for the repeating field:
```
nuxeo_default=# \d collectionobjects_common_fieldcollectionplaces
Table "public.collectionobjects_common_fieldcollectionplaces"
Column |         Type          | Collation | Nullable | Default 
--------+-----------------------+-----------+----------+---------
id     | character varying(36) |           | not null | 
pos    | integer …
```

DRYD-1395: Make fieldCollectionPlace repeatable

---

tomcat-main/src/main/resources/defaults/base-authority-concept.xml
tomcat-main/src/main/resources/defaults/extensions/fineart-authority-concept.xml
tomcat-main/src/main/resources/tenants/anthro/anthro-authority-concept.xml
tomcat-main/src/main/resources/tenants/herbarium/herbarium-authority-concept.xml
tomcat-main/src/main/resources/tenants/materials/materials-authority-concept.xml

This adds the concept/occasion vocabulary to all profiles that have the Use of Collections procedure (which has a field that references that vocabulary). Previously, the vocabulary was missing from fcart, anthro, herbarium, and materials.
Some profiles that had the Use of Collections procedure didn't have the Concept/Occasion vocabulary, so the Occasion field couldn't be filled in.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1400
In the fcart, anthro, herbarium, and materials tenants:
- On Create New, verify that Occasion is listed as a Concept 
- Create a Use of Collections record, and enter a value in the Occasion field. It should be …

DRYD-1400: Add concept/occasion viocab to all profiles that have uoc.

---

tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/botgarden/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/materials/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/publicart/base-instance-vocabularies.xml

Adds a vocab for the associated authority relation type
Jira: https://collectionspace.atlassian.net/browse/DRYD-1286
This adds a new vocabulary for use with the associated authority extension as the relationtypetype was deemed unsuitable. 
* Rebuild collectionspace with core, anthro, fcart, and lhmc enabled
* Check that the vocabulary exists for each tenant, e.g.
```
curl -u 'admin@core.collectionspace.org:Administrator' "http://localhost:8180/cspace-services/vocabularies/urn:cspace:name(assocauthorityrelationtype)/items"
```
None …

Add associated authority relation vocab

---

tomcat-main/src/main/resources/core-tenant.xml
tomcat-main/src/main/resources/default.xml
tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/base-procedure-summarydocumentation.xml
tomcat-main/src/main/resources/defaults/domain-procedure-summarydocumentation.xml

* Create summary documentation procedure
* Add summary documentation type term list
Jira: https://collectionspace.atlassian.net/browse/DRYD-1333
This adds the summary documentation procedure which is a necessary part of nagpra workflows.
* Run the integration test suite
* Ideally we should also be checking that once deployed the summary documentation api responds correctly, e.g.
* `curl http://localhost:8180/cspace-services/summarydocumentations`
`statusGroupType` will likely be a term list. It's currently a text type until we get clarification on …

DRYD-1333: Summary Documentation

---

tomcat-main/src/main/resources/core-tenant.xml
tomcat-main/src/main/resources/default.xml
tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/base-procedure-heldintrust.xml
tomcat-main/src/main/resources/defaults/domain-procedure-heldintrust.xml

* Create Held-in-Trust procedure
* Add terms for Held-in-Trust
* Enable Held-in-Trust for core
Jira: https://collectionspace.atlassian.net/browse/DRYD-1358
This adds the Held-in-Trust service as part of the nagpra workflows for 8.1. It also adds the necessary terms which will be used for some of the defined fields.
* Rebuild collectionspace with tenants enabled for running the integration tests
* Run the integration test suite
The `heldintrusttype` still needs to have terms defined. I've already reached out to Jessi to get some default terms.
**Has the application …

DRYD-1358: Held-in-Trust

---

tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/base-procedure-heldintrust.xml

* Adds cultural care fields to Held-in-Trust
* Update default values for heldintrusttype 
* Add limitationtype and limitationlevel terms to base vocabs
Jira: https://collectionspace.atlassian.net/browse/DRYD-1358
Instead of creating a new CulturalCare procedure, we're opting to pull the cultural care fields directly into Held-in-Trust. Along with this we're adding the existing term lists for cultural care into the base-vocabularies so that they can be used in core.
This is also updating the default terms for heldintrusttype, which we were previously waiting on.
* Use the cspace-ui PR to create a Held-in-Trust record with …

DRYD-1358: Held-in-Trust Updates

---

tomcat-main/src/main/resources/core-tenant.xml
tomcat-main/src/main/resources/default.xml
tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/base-procedure-consultation.xml
tomcat-main/src/main/resources/defaults/domain-procedure-consultation.xml

* Adds new procedure for consultation
* Add consultation terms
Jira: https://collectionspace.atlassian.net/browse/DRYD-1390
The consultation procedure is part of the 8.1 updates for improving NAGPRA workflows. It adds the ability to document the consultation process itself. 
* Rebuild collectionspace with the related services PR and tenants required for running integration tests
* Run the integration tests
I wasn't sure what to use for the `mini=summary` field, so hopefully the `involvedParty` is sufficient.
**Has the application documentation been updated for these …

DRYD-1390: Consultation

---

tomcat-main/src/main/resources/defaults/base-procedure-dutyofcare.xml

* Fix pluralization for duty of care
* Change title to dutyOfCareTitle
Jira: https://collectionspace.atlassian.net/browse/DRYD-1332
These changes come from the testing done against Duty of Care. The pluralization update which was requested is being applied here for consistency throughout the procedure. 
I also noticed that the `title` field exists in the dublin core schema, which was sometimes being pulled back in the search results, so I've updated the field definition to be `dutyOfCareTitle` to avoid that collision. I saw some procedures use `services-schema-qualift` with their title field, but I'm not _too_ familiar with what that's doing so I did a quick update of the name. Other NAGPRA procedures will likely hit the …

Duty of Care Updates

---

tomcat-main/src/main/resources/defaults/base-collectionobject.xml

* Add related link group to collectionobject
Jira: https://collectionspace.atlassian.net/browse/DRYD-1436
This adds related links to the reference information section for collectionobjects.
* Using the related cspace-ui PR: 
* Create a collectionobject and scroll to the Reference Information section
* See that the related link group exists and can be filled out
* Switch to the public browser template and see the same as the above
None
No …

DRYD-1436: Add related link group

---

tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml

* Add Deaccession Reason
* Add Exit Reason
* Add Exit Method
* https://collectionspace.atlassian.net/browse/DRYD-1480
* https://collectionspace.atlassian.net/browse/DRYD-1481
* https://collectionspace.atlassian.net/browse/DRYD-1484
These are new term lists which will be required for the new Deaccession and Object Exit procedures.
* Query the vocabularies endpoint for the new vocabs, e.g.
```
curl -u admin@core.collectionspace.org:Administrator "http://localhost:8180/cspace-services/vocabularies/urn:cspace:name(deaccessionreason)/items"
```
Will need to be added to …

ObjectExit and Deaccession Term Lists

---

tomcat-main/src/main/resources/defaults/base-procedure-heldintrust.xml

* Updates agreementGroup to be an enum type
Jira: https://collectionspace.atlassian.net/browse/DRYD-1358
Part of the initial QA updates was to update the agreementGroup to be controlled by `deaccessionapprovalgroup`. This updates the schema so that cspace is aware the field is being used as an enum type.
* Test with the related cspace-ui PR
None
No
@mikejritter tested against a local install

Held-in-Trust QA Updates

---

tomcat-main/src/main/resources/defaults/base-authority-concept.xml
tomcat-main/src/main/resources/defaults/base-procedure-nagprainventory.xml

* Add archculture concept to core
* Update affiliationGroupList name
* Set autocopmlete and enum on inventoryGroup
Jira: https://collectionspace.atlassian.net/browse/DRYD-1331
These are changes from initial testing of the NAGPRA Inventory procedure. While most of the changes are related to the ui layer, there were a few needed here. Notably `inventoryGroup` was supposed to be a controlled field and we needed to add `archculture` for use with `cultureGroupList`.
I also opted to simplify `culturalAffiliationGroupList` to just `affiliationGroupList`. This is shared in Summary Documentation but labelled as `summaryAffiliation`, so it seemed better to rename it.
**How should this be tested? Do these changes have associated …

NAGPRA Inventory QA Updates

---

tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml

* Remove nagprastatus
* Remove nagprainvstate
* Remove heldintruststatus
Jira: https://collectionspace.atlassian.net/browse/DRYD-1476
These are all term lists which were determined not to be necessary for the new NAGPRA workflows and are being removed.
* Test that the new terms don't exist, e.g.
```
curl -v -u admin@core.collectionspace.org:Administrator http://localhost:8180/cspace-services/vocabularies/urn:cspace:name(nagpra)
```
None
No
**Did someone actually run this code to verify it …

DRYD-1476: Remove unused term lists

---

tomcat-main/src/main/resources/defaults/base-procedure-summarydocumentation.xml

* Add enum tag to statusGroupType
* Rename culturalAffiliationGroup to affiliationGroup
Jira: https://collectionspace.atlassian.net/browse/DRYD-1333
These are changes that came from the initial testing that Jessi and Jadeen did.
Should be tested by the associated cspace-ui PR
None
No

SummaryDocumentation QA Updates

---

tomcat-main/src/main/resources/defaults/base-collectionobject.xml
tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/botgarden/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/materials/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/publicart/base-instance-vocabularies.xml

* Adds objectcountunit termlist
* Add objectCountUnit field
Jira: https://collectionspace.atlassian.net/browse/DRYD-1496
The objectCountUnit field that was supposed to be added when we updated the object count field group to be a larger group of fields.
* Test using the cspace-ui PR
None
No

DRYD-1496: Object Count Unit

---

tomcat-main/src/main/resources/anthro-tenant.xml
tomcat-main/src/main/resources/defaults/extensions/objectcategory-collectionobject.xml
tomcat-main/src/main/resources/defaults/extensions/objectcategory-vocabularies.xml
tomcat-main/src/main/resources/tenants/anthro/domain-instance-vocabularies.xml

* Add object category fields as an extension
* Add term list for object category
Jira: https://collectionspace.atlassian.net/browse/DRYD-1498
This is a new block of fields intended to be used with the anthro profile.
* Rebuild and start collectionspace with anthro enabled
* Test using the related cspace-ui pr
The extension namespace is kind of long, could be trimmed down. Not really a blocker though.
No

DRYD-1498: Object Category Extension

---

tomcat-main/src/main/resources/core-tenant.xml
tomcat-main/src/main/resources/default.xml
tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/base-procedure-deaccession.xml
tomcat-main/src/main/resources/defaults/domain-procedure-deaccession.xml

* Add deaccession procedure
* Update deaccession reason terms
Jira: https://collectionspace.atlassian.net/browse/DRYD-1355
The Deaccession procedure adds the ability to capture the decision making around removing an accessioned object. Previously this was part of the ObjectExit procedure, and this breaks it out into it's own procedure. 
* Rebuild and start collectionspace with all tenants required for integration tests
* Run the integration tests and ensure they pass
None
No
**Did someone actually run this code to verify it …

DRYD-1355: Deaccession Procedure

---

tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/botgarden/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/materials/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/publicart/base-instance-vocabularies.xml

* Corrects default terms for exit methods
* Corrects default terms for exit reasons
* Disambiguates new term lists from existing static lists
Jira: 
* https://collectionspace.atlassian.net/browse/DRYD-1484
* https://collectionspace.atlassian.net/browse/DRYD-1481
We added two new term lists in anticipation of the new Object Exit procedure which share the same name with an existing static term list. For clarity we decided it would be best to change the names of the lists so that they are different from the existing lists.
* Query for the new term lists
```
> curl -v --user admin@core.collectionspace.org:Administrator …
```

Update new Object Exit term lists

---

tomcat-main/src/main/resources/anthro-tenant.xml
tomcat-main/src/main/resources/core-tenant.xml
tomcat-main/src/main/resources/default.xml
tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/base-procedure-exit.xml
tomcat-main/src/main/resources/defaults/domain-procedure-exit.xml
tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
tomcat-main/src/main/resources/fcart-tenant.xml
tomcat-main/src/main/resources/lhmc-tenant.xml
tomcat-main/src/main/resources/materials-tenant.xml
tomcat-main/src/main/resources/tenants/botgarden/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/materials/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/publicart/base-instance-vocabularies.xml

* Add exit procedure definition
* Add exit agent term list
* Add new exit procedure to required profiles
Jira: https://collectionspace.atlassian.net/browse/DRYD-1356
The existing Object Exit procedure is being deprecated in favor of it being split into two procedures - the Deaccession and Object Exit. This handles the creation of a new Object Exit, named Exit, which will replace existing use.
* Pull the related services PR
* Rebuild and deploy collectionspace with the required tenants enabled for running the integration tests
* Start collectionspace and verify the endpoint is accessible
```
curl --user admin@core.collectionspace.org:Administrator …
```

DRYD-1356: New ObjectExit Procedure

---

tomcat-main/src/main/resources/defaults/base-instance-vocabularies.xml
tomcat-main/src/main/resources/defaults/extensions/fcart-profile-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/botgarden/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/materials/base-instance-vocabularies.xml
tomcat-main/src/main/resources/tenants/publicart/base-instance-vocabularies.xml

Update default terms in deaccessionapprovalstatus (Approval Status) term list to include the option "partially approved"  
Jira ticket: https://collectionspace.atlassian.net/browse/DRYD-1474
- Re-build and deploy collectionspace
- Start collectionspace
- Create New -> Procedures -> Deaccession
- Under Deaccession approval, see Status pulldown has new option "partially approved" (see attached screenshot)
None
No
@axb21 tested as per above procedure (see screenshot) …

DRYD-1474: added term 'partially approved' to deaccessionapprovalstatus

---

tomcat-main/src/main/resources/defaults/base-procedure-claim.xml
tomcat-main/src/main/resources/defaults/base-procedure-objectexit.xml
tomcat-main/src/main/resources/defaults/base-procedure-osteology.xml

* Add legacy tag to ObjectExit, Osteology, and Claim
Jira: https://collectionspace.atlassian.net/browse/DRYD-1595
As part of the updates to the Create Page and new procedures for 8.1, we want to let users know that certain procedures will be considered legacy and should not be preferred. Since we handled the NAGPRA procedures by adding a tag attr to the xml, we've done the same here by adding the tag attr to Object Exit, Osteology, and Claim.
* Query for legacy procedures, e.g.
```
curl -H "Accept: application/json" -v --user admin@core.collectionspace.org:Administrator …
```

DRYD-1595: Add legacy tag to procedures

---

tomcat-main/src/main/resources/anthro-tenant.xml
tomcat-main/src/main/resources/fcart-tenant.xml
tomcat-main/src/main/resources/lhmc-tenant.xml
tomcat-main/src/main/resources/materials-tenant.xml

The Deaccession procedure is now available in the anthro, fcart, lhmc, and materials profiles.
JIRA ticket DRYD-1553, https://collectionspace.atlassian.net/browse/DRYD-1553
- Pull this commit
- Stop CSpace, re-deploy, start CSpace
- For each of the anthro, fcart, lhmc, and materials UI plugins:
- Launch the plugin (`npm run devserver` in the plugin's directory)
- Login to the profile
- Click Create New
- See "Deaccession" listed in the available procedures
- Click "Deaccession" and see that the expected page is shown
None
No
**Did …

DRYD-1553: added deaccession procedure include to anthro, fcart, lhmc and materials tenant configurations

---

tomcat-main/src/main/resources/defaults/extensions/anthro-profile-instance-vocabularies.xml

* Adds lineal descendant to object count types
Jira: https://collectionspace.atlassian.net/browse/DRYD-1514
Lineal descendant is used in the repatriation request consultation report, but was previously unable to be populated because the term did not exist. This adds the term to the object count types list.
* Rebuild and start collectionspace with anthro enabled
* Query using the anthro admin for objectcounttypes and see lineal descendant
None
No
No

Add lineal descendant to object count types

---

tomcat-main/src/main/resources/defaults/base-procedure-osteology.xml

* Remove the legacy tag from osteology
Jira: https://collectionspace.atlassian.net/browse/DRYD-1595
Although osteology is not as good as it could be, it is not ready to be marked as legacy. This undoes the original changes from DRYD-1595.
* See that osteology does not have the legacy tag in profiles where it is used
None
No

Remove legacy tag from osteology

---

tomcat-main/src/main/resources/defaults/base-procedure-consultation.xml

* Set ui-type for reason field
Jira: https://collectionspace.atlassian.net/browse/DRYD-1618
We noticed in our regression testing that consultations were throwing an error related to the `consultationreason`. This was actually from the `reason` field showing up in the related terms even though it is not an authority. The fix for this is to set `ui-type="enum"` so that when the service bindings are being generated the `authRef` property is not included on the field.
* Create a Consultation with a consultation reason
* On save, notice the `Terms Used` panel will have a single result
* If the panel is expanded you'll get an …

Set ui-type for reason

---

tomcat-main/src/main/resources/tenants/botgarden/botgarden-procedure-objectexit.xml

* Remove the service tag for object exit in botgarden
Jira: https://collectionspace.atlassian.net/browse/DRYD-1625
The botgarden tenant renames object exit and as such it shouldn't be marked as deprecated. 
* Rebuild and start collectionspace with the botgarden tenant enabled
* Check the servicegroups endpoint to see if object exit is included in the 'legacy' tags
```
curl --user admin@botgarden.collectionspace.org:Administrator "http://localhost:8180/cspace-services/servicegroups/procedure?servicetag=legacy" -H "Accept: application/json" | jq .
```
Not a dependency but honestly it's confusing to …

DRYD-1625: Remove objectexit service tag in botgarden 

---

tomcat-main/src/main/resources/publicart-tenant.xml
tomcat-main/src/main/resources/tenants/publicart/base-instance-vocabularies.xml

* Add new deaccession and object exit procedures to publicart profile
Jira: https://collectionspace.atlassian.net/browse/DRYD-1624
These were initially missed during the 8.1 release and are being added to the publicart profile.
* Rebuild and start collectionspace with the publicart tenant enabled
* Check that both procedures are now able to be queried for
```
curl --user admin@publicart.collectionspace.org:Administrator http://localhost:8180/cspace-services/deaccessions
curl --user admin@publicart.collectionspace.org:Administrator http://localhost:8180/cspace-services/exits
```
Needs verification in …

DRYD-1624: Add deaccession and object exit to publicart
